#!/usr/bin/env bash
#
# sync-env.sh — sinh file `bruno/.env` (gitignored) để Bruno nạp qua {{process.env.*}}.
# Đọc PORT từ backend .env và fetch publishable key từ Postgres đang chạy (docker).
#
# Dùng:  ./bruno/scripts/sync-env.sh
# Override:  PG_CONTAINER=... PG_USER=... PG_DB=... ./bruno/scripts/sync-env.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRUNO_DIR="$(dirname "$SCRIPT_DIR")"
ROOT_DIR="$(dirname "$BRUNO_DIR")"
BACKEND_ENV="$ROOT_DIR/hf-medusa-store/apps/backend/.env"

# --- PORT từ backend .env (fallback 9009) ---
PORT=""
if [[ -f "$BACKEND_ENV" ]]; then
  PORT="$(grep -E '^PORT=' "$BACKEND_ENV" | head -1 | cut -d= -f2- | tr -d '\r[:space:]')"
fi
PORT="${PORT:-9009}"
BASE_URL="http://localhost:${PORT}"

# --- Publishable key từ Postgres trong container ---
PG_CONTAINER="${PG_CONTAINER:-hf_medusa_postgres}"
PG_USER="${PG_USER:-hfmedusa}"
PG_DB="${PG_DB:-hfmedusa}"

PUBKEY="$(docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" -tAc \
  "select token from api_key where type='publishable' and revoked_at is null order by created_at limit 1" \
  | tr -d '\r[:space:]')"

if [[ -z "$PUBKEY" ]]; then
  echo "⚠  Không tìm thấy publishable key trong DB — chạy 'pnpm backend:seed' trước." >&2
fi

OUT="$BRUNO_DIR/.env"
{
  echo "# Auto-generated by bruno/scripts/sync-env.sh — DO NOT COMMIT (gitignored)."
  echo "BASE_URL=${BASE_URL}"
  echo "PUBLISHABLE_KEY=${PUBKEY}"
} > "$OUT"

echo "✔ Wrote $OUT"
echo "  BASE_URL=$BASE_URL"
echo "  PUBLISHABLE_KEY=${PUBKEY:0:7}…(${#PUBKEY} chars)"
