import { MedusaRequest, MedusaResponse } from "@medusajs/framework/http";
import { readFile } from "fs/promises";
import path from "path";

/**
 * GET /docs/openapi/core — serves the Medusa CORE API OAS (admin + store),
 * generated by `@medusajs/medusa-oas-cli` into `apps/backend/oas/combined.oas.json`.
 *
 * Regenerate with:  pnpm --filter @dtc/backend oas
 * (runs: medusa-oas oas --type combined --out-dir ./oas)
 *
 * The file is large (~320 paths) so it is read from disk lazily and cached in
 * memory for the process lifetime rather than imported/bundled. If it hasn't
 * been generated yet, returns 503 with a hint instead of crashing.
 *
 * Public (no auth): /docs is not under /admin or /store, so no auth runs.
 */
let cached: unknown | null = null;

// medusa develop runs with cwd = apps/backend, where the oas/ folder lives.
const OAS_PATH = path.join(process.cwd(), "oas", "combined.oas.json");

export const GET = async (_req: MedusaRequest, res: MedusaResponse) => {
  if (!cached) {
    try {
      cached = JSON.parse(await readFile(OAS_PATH, "utf8"));
    } catch {
      res.status(503).json({
        message:
          "Core OAS not generated yet. Run `pnpm --filter @dtc/backend oas` " +
          "to create apps/backend/oas/combined.oas.json.",
      });
      return;
    }
  }
  res.json(cached);
};
